# -*- coding: utf-8 -*-
"""ecom-proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BUxCqXz0nYidM2UelsUFwwjaC4YKLv2
"""

import pandas as pd
import numpy as np
import datetime as dt

#Load
fi=pd.read_csv("/content/data.csv", encoding= 'ISO-8859-1')
fi

fi.isnull().sum()

#Clean
fi.dropna(subset=['CustomerID'], inplace=True)
fi=fi[(fi['Quantity']>0) & (fi['UnitPrice']>0)]

#Feature Engineering
fi['TotalSpend']=fi['Quantity']*fi['UnitPrice']
#when pandas read csv it treats dates as plain text, so u cant do math on tect(like subtracting days)
fi['InvoiceDate']=pd.to_datetime(fi['InvoiceDate'])#this keyword converts text into actionable date objects

#Setting Timeline
snapshot_date=fi['InvoiceDate'].max()+dt.timedelta(days=1)
# 'max()' finds the absolute latest timestamp in the entire dataset
#'dt.timedelta(days=1)' adds exactly 1 day to that latest timestamp
# did it so to pretend i am running this script 1 day after the data is pulled
#this ensures that a customer who bought something on the last day gets a Recency score of '1 day ago' instead of '0 days ago'

#calculate R.F.M Metrics
#groupby('CustomerID') is very imp keyword. it takes 1000s of rows of transactions and clusters them so there is only 1 row per unique customer
#.agg() allows us to perform diff math ops on diff columns simultaneously
rfm=fi.groupby('CustomerID').agg({
    #Recency: used 'lambda' function(temporary and unnamed function)
    #'x' represents the customer's dates. to find their most recent purchases uing x.max()
    #subtract it from our snapshot_date and use days to extract just the integer no.of days
    'InvoiceDate':lambda x: (snapshot_date - x.max()).days,
    #Frequency: used 'nunique'(no.of unique). for eg: a customer might buy 5 items in one order(5 rows)
    #dont want to count 5 orders. 'nunuique' counts the unique invoive nums so to understand how many times they checcked out
    'InvoiceNo': 'nunique',
    #Monetary: used 'sum' to simply add up all the money in the TotalSpend column for that one specific customer
    'TotalSpend':'sum'
    #.reset_index() is used cos groupby() makes the CustomerID the hidden "row label"
    #this command pushes CustomerID back out to into a normal, visible column so PowerBI can read it
}).reset_index()

#format 4 dashboard
rfm.rename(columns={'InvoiceDate':'recency','InvoiceNo':'Frequency','TotalSpend':'Monetary'}, inplace=True)
#changed names to enssure that when imported to powerbi the dashboard fields automatically have professonal names

#Export
rfm.to_csv('rfm4bi.csv', index=False)#.to_csv() takes the final aggregated dataframe and saves it to computer as a new file
print("RFM Calculation Complete! File Saved!")#index=false is crucial, w/o it pandas will write the row nums as an xtra useless column in the csv